runtime: nodejs18
handlers:
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico
  # Serve all static files with url ending with a file extension
  - url: /
    static_files: build/index.html
    upload: build/index.html
    static_dir: build
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/\1
  # Catch all handler to index.html
  - url: /.+
    static_files: build/index.html
    upload: build/index.html